chore: update action

diff --git a/.github/workflows/create-pull-request.yml b/.github/workflows/create-pull-request.yml
--- a/.github/workflows/create-pull-request.yml
+++ b/.github/workflows/create-pull-request.yml
@@ -20,4 +20,6 @@ jobs:
 
       - name: Check Latest Release Branch
         if: env.latest_branch_name == null
-        run: exit 1
+        run: |
+          echo "Error: There is no release branch to request."
+          exit 1
