fix pr

diff --git a/.github/workflows/create-pull-request.yml b/.github/workflows/create-pull-request.yml
--- a/.github/workflows/create-pull-request.yml
+++ b/.github/workflows/create-pull-request.yml
@@ -33,6 +33,35 @@ jobs:
           pr_label: "feature"
           pr_draft: true
 
+  create-fix-pull-request:
+    if: ${{ startsWith(github.ref_name, 'fix/') }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Set environment variables
+        run: |
+          git fetch
+          echo "issue_id=$(echo '${{ github.ref_name }}' | cut -d '/' -f 2)" >> $GITHUB_ENV
+          echo "latest_release_branch=$(git branch -a | grep -E -o 'release/[0-9]*' | sort -r | head -1 | tr -d ' ')" >> $GITHUB_ENV
+
+      - name: Check latest release branch exists
+        if: env.latest_release_branch == null
+        run: |
+          echo "::error::There is no release branch to request."
+          exit 1
+
+      - name: Create pull request
+        uses: repo-sync/pull-request@v2
+        with:
+          destination_branch: ${{ env.latest_release_branch }}
+          pr_title: "[fix][${{ env.issue_id }}] Automatically Created Fix PR"
+          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"
+          pr_assignee: ${{ github.actor }}
+          pr_label: "fix"
+          pr_draft: true
+
   create-hotfix-pull-request:
     if: ${{ startsWith(github.ref_name, 'hotfix/') }}
     runs-on: ubuntu-latest
